### ISSUE TITLE
Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8876.

### ISSUE THREAD

**Issue by mattqs** [Quobject/explorer#1]
Error @ Mon, 05 Feb 2018 18:46:06 GMT
System.Data.SqlServerCe.SqlCeException (0x80004005): Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8876. Install the correct version of SQL Server Compact. Refer to KB article 974247 for more details.
   at System.Data.SqlServerCe.NativeMethods.LoadNativeBinaries()
   at System.Data.SqlServerCe.SqlCeConnection..ctor()
   at System.Data.SqlServerCe.SqlCeProviderFactory.CreateConnection()
   at System.Data.Entity.Infrastructure.SqlCeConnectionFactory.CreateConnection(String nameOrConnectionString)
   at System.Data.Entity.Internal.LazyInternalConnection.Initialize()
   at System.Data.Entity.Internal.LazyInternalConnection.get_ProviderName()
   at System.Data.Entity.Internal.LazyInternalContext.get_ProviderName()
   at System.Data.Entity.Internal.DefaultModelCacheKeyFactory.Create(DbContext context)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.Generic.IEnumerable<TResult>.GetEnumerator()
   at Explorer.Model.Operations.QuestionEntityConsistencyCheckOperation.Main() in c:\Development\quobject.visualstudio.com\eris\MSDesktopApplications\Explorer\Model\Operations\QuestionEntityConsistencyCheckOperation.cs:line 29
   at Explorer.Model.Operations.OperationBase.<RunMainTask>b__0() in c:\Development\quobject.visualstudio.com\eris\MSDesktopApplications\Explorer\Model\Operations\OperationBase.cs:line 17
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Explorer.Model.Operations.OperationsQueue.<RunOperations>d__0.MoveNext() in c:\Development\quobject.visualstudio.com\eris\MSDesktopApplications\Explorer\Model\Operations\OperationsQueue.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mattqs** [comment]
Reproduced error on fresh windows 10 install

**Comment by mattqs** [comment]
Fixed in 1.5.7.2
